# 什么是pytorch
这是一个基于python的科学计算包，主要目标人群为以下两类：
作为NumPy的替代，可以使用GPUs的计算能力
深度学习研究的框架，提供了最大的灵活性和速度
## 开始
### 张量（Tensors）
Tensors和NumPy’s ndarrays相似，不同的是Tensors可以运用GPU来加速计算。

In [1]:
from __future__ import print_function
import torch

构造一个5x3未初始化的矩阵：

In [4]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-26 *
       [[ 0.0000, -0.0025,  0.0000],
        [-0.0025,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000, -0.0025,  7.7728]])


构造一个随机初始化的矩阵：

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.8987,  0.6507,  0.7564],
        [ 0.1852,  0.3247,  0.1079],
        [ 0.6179,  0.1244,  0.7323],
        [ 0.2600,  0.2738,  0.9946],
        [ 0.5425,  0.2615,  0.7494]])


构建一个的type为long型的0矩阵：

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


通过数据直接构建一个tensor：

In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


或者通过已有的tensor构建一个tensor。这个方法会重用输入tensor的特性不管新的特性是否被提供，如：dtype

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 1.8788, -0.3926, -0.3271],
        [-1.4083, -0.3068, -1.3775],
        [ 1.3464, -1.3524,  1.1285],
        [-0.8659, -1.5281,  1.6387],
        [ 0.3340, -0.3239,  0.2766]])


获得tensor的size：

In [11]:
print(x.size())

torch.Size([5, 3])


**<font color=red>注意</font>**：torch.Size实际上是个元组（tuple），所以支持元组的所有操作

### 操作（operations）

操作的语法有有多种。在下面的例子中，我们看一下加法操作。
#### 加法：语法一

In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.9799, -0.1989, -0.0009],
        [-1.0011,  0.5705, -1.0863],
        [ 1.4238, -0.9299,  2.0147],
        [-0.2509, -1.0759,  2.4035],
        [ 0.8495, -0.2571,  0.6317]])


#### 加法：语法二

In [13]:
print(torch.add(x, y))

tensor([[ 1.9799, -0.1989, -0.0009],
        [-1.0011,  0.5705, -1.0863],
        [ 1.4238, -0.9299,  2.0147],
        [-0.2509, -1.0759,  2.4035],
        [ 0.8495, -0.2571,  0.6317]])


#### 加法：提供一个输出tensor作为参数

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.9799, -0.1989, -0.0009],
        [-1.0011,  0.5705, -1.0863],
        [ 1.4238, -0.9299,  2.0147],
        [-0.2509, -1.0759,  2.4035],
        [ 0.8495, -0.2571,  0.6317]])


#### 加法：原地操作（in-place)

In [15]:
y.add_(x)
print(y)

tensor([[ 1.9799, -0.1989, -0.0009],
        [-1.0011,  0.5705, -1.0863],
        [ 1.4238, -0.9299,  2.0147],
        [-0.2509, -1.0759,  2.4035],
        [ 0.8495, -0.2571,  0.6317]])


**<font color=red>注意</font>**：任何带有一个 \_ 后缀的操作都会原地（in-place)改变tensor的值。例如x.copy_(y), x.t_() 将会改变x。

你可以用标准的带有各种各样技巧的Numpy形式（Numpy-like)的索引方式（indexing）！

In [16]:
print(x[:, 1])

tensor([-0.3926, -0.3068, -1.3524, -1.5281, -0.3239])


改变形状（resizing）：如果你想改变tensor的形状（resize/reshape），你可以用torch.view:

In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个只有一个值得tensor，用 .item() 来获取Python的数值

In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2379])
-0.23787488043308258


**后续阅读：**
100+ 的 Tensors 操作，包括转置（transposing）、索引（indexing）、切片（slicing）、数学操作（mathematical operations）、线性代数（linear algebra）、随机数（random numbers）等等我们可以在[这里](https://pytorch.org/docs/stable/torch.html)找到

## NumPy 之间的桥梁
在Torch的Tensor和NumPy array之间的转换非常简单
Torch Tensor 和 NumPy array 会共享他们潜在的内存位置， 改变其中一个将会改变另一个。
### 从 Torch Tensor 到 NumPy Array 的转换

In [21]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


看看 NumPy array 值的改变

In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


### 从 NumPy Array 到 Torch Tensor 的转换

In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


所有在 CPU 上的 Tensors（除了 CharTensor）都支持与 NumPy 之间的相互转换。

## CUDA Tensors
Tensors 可以用 .to 方法移动到任何设备上。

In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!